version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/local_service_db
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
